site_name: metagrid
site_description: ESGF Search UI
repo_url: https://github.com/aims-group/MetaGrid
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/aims-group">aims-group</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
