site_name: MetaGrid
site_description: ESGF Search UI
repo_url: https://github.com/esgf2-us/metagrid
site_dir: site
dev_addr: 0.0.0.0:8001
theme: readthedocs
markdown_extensions:
- mdx_truly_sane_lists
- admonition
- toc:
    permalink: ÔÉÅ

nav:
- Home: "index.md"
- User Guide:
  - Quickstart: "users/quickstart.md"
  - Moving to Production: "users/moving_to_production.md"
  - Configurable environment variables: "users/configurable_environment_variables.md"
- Contributor Guide:
  - Project Standards: "contributors/project_standards.md"
  - Architecture Design: "contributors/architecture_design.md"
  - Getting Started For Local Development: "contributors/getting_started_local.md"
  - Back-end Development: "contributors/backend_development.md"
  - Front-end Development: "contributors/frontend_development.md"
  - Documentation: "contributors/document.md"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
